---
title: "Forthcoming in journals"
author: "Adriano M R Figueiredo"
date: '2020-01-13'
categories: []
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2020-01-13T19:56:18-04:00'
projects: []
slug: forthcoming-in-journals
subtitle: ''
summary: ''
tags:
- artigos aceitos
- papers
- journals
authors: []
---


## Artigos aceitos para publicação        


1.	 Fagundes, Mayra Batista Bitencourt; SILVA JUNIOR, E. A.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; MACHADO, J. V.. 2019.
COMPLEXIDADE ECONÔMICA REGIONAL: UMA ABORDAGEM A PARTIR DE DADOS DE EMPREGO In RDE. Revista de Desenvolvimento Econômico.
Palavras-chave: complexidade economica, Mato Grosso do Sul, emprego
Áreas do conhecimento: Economia Regional,Métodos e Técnicas do Planejamento Urbano e Regional
Setores de atividade: Administração pública, defesa e seguridade social
Referências adicionais: Português.
aceito para publicação no numero 43 da RDE    

2.	 Dallemole Dilamar; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2019.
The Consumer Profile and Car Insurance Market of Cuiabá, Brasil In Estudios de Economía Aplicada.
Palavras-chave: car insurance, consumer profile, market, Cuiabá
Áreas do conhecimento: Economia Regional e Urbana,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Economia do Consumidor
Setores de atividade: Administração pública, defesa e seguridade social
Referências adicionais: Português.    

3.	 MUCELLINI, A. B.; BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.. 2007.
Sistemas e custos de produção da bovinocultura de corte no município de Alta Floresta – Mato Grosso In Geicor Business Review.
Palavras-chave: pecuária de corte, custos de producao, Alta Floresta
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal
Referências adicionais: Português.
