---
title: "Papers in Conferences"
author: "Adriano M R Figueiredo"
date: '2020-01-13'
categories: []
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2019-12-23T19:56:18-04:00'
projects: []
slug: papers-in-conferences
subtitle: ''
summary: ''
tags:
- artigos publicados
- papers
- conferences
authors: []
---

    

## Trabalhos publicados em anais de eventos (completo)     
     
     
1.	 SILVA JUNIOR, E. A.; FAGUNDES, Mayra Batista Bitencourt; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; MACHADO, J. V.. 2019.
COMPLEXIDADE ECONÔMICA REGIONAL: UMA ABORDAGEM A PARTIR DE DADOS DE EMPREGO In Anais do 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL Ilhéus-BA 2019 57 1 Ilhéus-BA: SOBER/UESC
Palavras-chave: índice de complexidade econômica, Desenvolvimento Regional, diversidade
Áreas do conhecimento: Economia Regional e Urbana,Métodos e Técnicas do Planejamento Urbano e Regional
Setores de atividade: Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://https://icongresso.itarget.com.br/tra/arquivos/ser.9/1/9702.pdf]
O presente artigo utiliza-se de informações sobre a estrutura produtiva dos municípios de Estado de Mato Grosso do Sul em 2006 e 2016 para propor uma medida de sofisticação econômica como apresentado por Hausmann et al. (2011), o Índice de Complexidade Econômica – ICE. Para tal, adapta-se o método original de forma que o tradicional escopo de dados de comércio internacional seja substituído por informações relacionadas ao emprego formal, uma vez que à realidade municipal, tais informações demonstram aderir-se de maneira mais eficiente à captação da estrutura produtiva. O indicador proposto no trabalho observou que, em geral, há um movimento de diversificação da economia sul-mato-grossense, no entanto, não suficiente para observar crescimento dos níveis de sofisticação relevantes, no período analisado.    

2.	 BERTOLDO, W. L.; FAGUNDES, Mayra Batista Bitencourt; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; FRAINER, D. M.. 2019.
EVOLUÇÃO DA BALANÇA COMERCIAL DO ESTADO DE MATO GROSSO DO SUL: UMA ANÁLISE PELO MODELO CONSTANT MARKET SHARE In Anais do 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL Ilhéus-BA 2019 57 1 Ilhéus-BA: SOBER/UESC
Palavras-chave: competitividade, comércio internacional, Agronegócio
Áreas do conhecimento: Economia Agrária,Métodos e Técnicas do Planejamento Urbano e Regional,Economia Internacional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://https://icongresso.itarget.com.br/tra/arquivos/ser.9/1/9697.pdf]
O objetivo deste estudo foi analisar a evolução da balança comercial interestadual e internacional do estado do Mato Grosso do Sul para os períodos de 2012 a 2017. O estudo teve como base teórica os trabalhos sobre desenvolvimento regional de Perroux, Hirschman e em especial da teoria da base exportadora de Douglass North. A metodologia quantitativa adotada para se alcançar o objetivo proposto foi o modelo constant market share. Além disso, a fonte dos dados utilizados é secundária e proveniente do Ministério do Desenvolvimento, da Indústria e do Comércio Exterior (MDIC) e Secretaria de Estado de Meio Ambiente, Desenvolvimento Econômico, Produção e Agricultura (SEMAGRO/MS). Os resultados mostram que, no que tange o fluxo comercial agregado, Mato Grosso do Sul tem ganhado espaço no mercado interno e externo ao apresentar um crescimento das exportações de quase 50% no período. Não obstante, nas relações interestaduais o estado de São Paulo e a região sul ainda são os principais parceiros comerciais com saldo positivo para o estado, embora as regiões Norte e Nordeste ganhem participação na exportação e na importação de produtos provenientes da região Sul-Mato-Grossense. Conclui-se que a maior participação do estado, tanto nas exportações interestaduais quanto nas internacionais, mostra ganhos de competitividade dos produtos produzidos na região.    

3.	 ZADUSKI, J. S.; FAGUNDES, Mayra Batista Bitencourt; MOTOBAYASHI, F. I.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2019.
O EFEITO DO TABELAMENTO DO FRETE NOS CUSTOS DE TRANSPORTE DA SOJA EM GRÃOS DO ESTADO DE MATO GROSSO DO SUL In Anais do 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL Ilhéus-BA 2019 57 1 Ilhéus-BA: SOBER/UESC
Palavras-chave: logística, Agronegócio, frete
Áreas do conhecimento: Economia Agrária,Ciências Contábeis,Economia dos Transportes
Setores de atividade: Transporte terrestre, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://https://icongresso.itarget.com.br/tra/arquivos/ser.9/1/9549.pdf]
Este trabalho procurou analisar as variáveis que interferem no custo do transporte da soja produzida nos sete principais municípios produtores de soja estado do Mato Grosso do Sul e comparar o resultado obtido com o Tabelamento do Frete, proposto pelo Governo, do intuito de verificar se ele cobre os custos operacionais dos transportadores. Para responder ao objetivo proposto utilizou-se do método quantitativo descritivo, relatando e calculando variáveis como: depreciação, IPVA, salários, seguros, custos com empréstimos, lavagens, valores gastos com combustível, pneus e óleos. Os resultados mostram que quando comparados os dados para uma distância de até, aproximadamente, 1200 km o tabelamento é desvantajoso para os transportadores, porém à medida que esta distância aumenta este valor começa a ser vantajoso e cobrir os custos necessários. Portanto para os municípios analisados, que possuem, em sua maioria, distância média menor que 1200 km, este tabelamento não é eficiente para os transportadores de soja que circulam no Estado do Mato Grosso do Sul.    

4.	 FIGUEIREDO, ADRIANO MARCOS RODRIGUES; MOTA, A. C. P.; PADILHA, D. T.; NARDINO, F. P.. 2019.
UMA ANÁLISE E PREVISÃO DO CRÉDITO RURAL DE CUSTEIO PARA MATO GROSSO (2019-2021) In Anais do 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL 57º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL Ilheus-BA 2019 57 1 Ilhéus-BA: SOBER/UESC
Palavras-chave: crédito rural, previsão, custeio
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Séries Temporais
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://https://icongresso.itarget.com.br/tra/arquivos/ser.9/1/9690.pdf]
O crédito rural é uma alternativa utilizada por muitos produtores no Brasil no intuito de financiar a atividade produtiva ou parte dela. Visando analisar a relação entre crédito rural de custeio e crescimento da atividade agropecuária, bem como realizar um previsão de demanda para o crédito nesta modalidade durante os próximos 03 anos (2019 a 2021), utilizou-se os dados trimestrais nominais do Sistema de Contas Nacionais Trimestrais a nível Brasil para o período compreendido entre o primeiro trimestre de 2013 ao terceiro trimestre de 2018, além da série de dados mensais, que foram transformados em trimestrais de quantidade e valor do crédito rural de custeio para Mato Grosso no mesmo período. Como resultado, a previsão da demanda de crédito agrícola de custeio realizada através do pacote de ajuste sazonal X13ArimaSeats, para o estado de Mato Grosso, apresentou cerca de 34,97 bilhões de reais necessários nos próximos 03 anos para que a demanda dos produtores do estado por credito rural nesta modalidade sejam atendidas.    

5.	 ROLAO, K. P.; FIGUEIREDO NETO, L. F.; ROSA, R. O.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2018.
ANÁLISE COMPARATIVA ENTRE O SISTEMA DE ARROZ IRRIGADO E SISTEMA DE ARROZ SEQUEIRO In 56º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL -SOBER 56º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL -SOBER Campinas-SP 2018 56 1-20 Brasília: SOBER/UNICAMP
Palavras-chave: análise de custos, sistema irrigado, sistema sequeiro
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.8/1/9256.pdf]    

6.	 FIGUEIREDO, ADRIANO MARCOS RODRIGUES; FAGUNDES, Mayra Batista Bitencourt; FIGUEIREDO NETO, L. F.. 2018.
EFEITOS DE BARREIRAS COMERCIAIS SOBRE A SOJA E A CARNE: OS CENÁRIOS DE EMBARGOS DA CHINA, UNIÃO EUROPEIA E ESTADOS UNIDOS In 56º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL -SOBER 56º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL -SOBER Campinas-Sp 2018 56 1-19 Brasília: SOBER/UNICAMP
Palavras-chave: embargo, PAEG, MPSGE
Áreas do conhecimento: Economia Agrária,Economia Internacional,Economia Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.8/1/8460.pdf]
Os fluxos comerciais brasileiros aumentaram nos últimos anos, mesmo com altas tarifas e barreiras comerciais não-tarifárias. Avaliam-se os efeitos do embargo imposto à carne brasileira e aos cereais (grãos e oleaginosas). Especificamente analisa-se o comércio regional brasileiro e seus principais indicadores, como a produção, os preços das commodities e fatores, PIB, e bem-estar. O modelo analítico é baseado em um modelo de equilíbrio geral computável chamado PAEG que permite a análise das regiões brasileiras, as suas relações com outros países ou blocos econômicos, utilizando o banco de dados na versão 9 do GTAP. Os resultados mostram que o embargo chinês sobre os grãos (soja e outros) brasileiros levaria a uma diminuição do consumo destes na China de cerca de USD 750 milhões. Em relação às regiões brasileiras ocorreu redução nas exportações ( -USD 250 milhões) no Centro-Oeste, mas aumentou as exportações da região Sudeste (USD 690 milhões), principalmente de produtos manufaturados e roupas. Quanto aos embargos da UE e dos EUA à carne brasileira, observase que os impactos são menores do que os resultantes do embargo chinês sobre os grãos brasileiros. O embargo americano causaria mais danos do que o europeu. Os EUA enfrentariam perdas de bem-estar, tornando-se mais sensível do que a União Europeia, em relação à carne brasileira.    

7.	 FIGUEIREDO, ADRIANO MARCOS RODRIGUES; FAGUNDES, Mayra Batista Bitencourt; FIGUEIREDO NETO, L. F.. 2018.
EFFECTS OF TRADE BARRIERS ON BRAZILIAN SOYBEAN AND MEAT: The cases of China, EU and US embargoes In Annals of the 26th Conference of the International Input Output Association IIOA 26th Conference of the International Input Output Association IIOA Juiz de Fora-MG 2018 26 1-2 Vienna, Austria: IIOA
Palavras-chave: embargo, PAEG, MPSGE, meat, soybean
Áreas do conhecimento: Economia Regional,Economia Internacional,Métodos e Técnicas do Planejamento Urbano e Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Austria/Inglês. Meio de divulgação: Meio digital. Home page: [http://https://www.iioa.org/conferences/conferences.html]
Brazilian trade flows have increased in recent years, even with high tariffs and non-tariff trade barriers. The present study evaluated the effects of embargoes imposed on Brazilian meat and cereals (grains and oilseeds). Specifically, the Brazilian regional trade and its main indicators such as production, prices of commodities and factors, gross domestic product (GDP), and welfare were analyzed. The analytical model was based on a computable general equilibrium model - General Equilibrium Analysis Project for the Brazilian Economy (PAEG), which enables Brazilian regions and their relations with other countries or economic blocks to be analyzed using the GTAP 9.0 database. The results showed that the Chinese embargo on Brazilian grains (soybean and others) would lead to a decrease in their consumption in China of around USD 750 million. Regarding Brazilian regions, a reduction in exports (-USD 250 million) was observed in Central West, while an increase in exports was detected in Southeast (USD 690 million), mainly of manufactured products and clothing. As to embargoes of the European Union (EU) and the United States (U.S.) on Brazilian meat, impacts were lower than those resulting from the Chinese embargo on Brazilian grains. The U.S. embargo would lead to greater damages than the European one. The United States would face welfare losses, becoming more sensitive than the EU in relation to Brazilian meat. Keywords: embargo, PAEG, MPSGE, meat, soybean.    

8.	 FAGUNDES, Mayra Batista Bitencourt; OLIVEIRA, D. V.; DIAS, D. T.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2018.
ÍNDICE DE CONCENTRAÇÃO NORMALIZADO DA PECUÁRIA NOS MUNICÍPIOS DE MATO GROSSO DO SUL In 56º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL -SOBER 56º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÃO E SOCIOLOGIA RURAL -SOBER Campinas-SP 2018 56 1-20 Brasília: SOBER/UNICAMP
Palavras-chave: Agronegócio, Desenvolvimento Regional, bovinocultura, avicultura, suinocultura
Áreas do conhecimento: Economia Agrária,Economia Regional,Métodos e Técnicas do Planejamento Urbano e Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.8/1/9213.pdf]    

9.	 SILVA, C. E. S. F.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; FAGUNDES, Mayra Batista Bitencourt; FIGUEIREDO NETO, L. F.. 2018.
MANUFACTURED GOODS, MEATS AND GRAINS: ALTERNATIVES TO A BILATERAL AGREEMENT BETWEEN MERCOSUR AND CHINA In Annals of the 26th Conference of the International Input Output Association IIOA 26th Conference of the International Input Output Association IIOA Juiz de Fora-MG 2018 26 1-2 Vienna, Austria: IIOA
Palavras-chave: Preferential Trade Agreement, GTAPinGAMS, PAEG
Áreas do conhecimento: Economia Regional,Economia Agrária,Economia Internacional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Inglês. Meio de divulgação: Meio digital. Home page: [http://https://www.iioa.org/conferences/conferences.html]
This study aimed at identifying a possible bilateral agreement between Mercosur and China and its respective impacts on their economies. To this end, the General Equilibrium Analysis Project for the Brazilian Economy (PAEG) was used to conduct tariff reduction scenarios of 25, 50 and 75% of Mercosur agribusiness products such as soybean, corn and meat, together with the Chinese manufacturing sector, with household disaggregation. A tariff reduction scenario of 75% in the Brazilian meat industry and in the Chinese manufacturing sector led to the best results for the Brazilian economy, since the agreement (oap/man) would result in the highest gross domestic product growth rate and would reach industries more positively. However, the agreement (osd/man) involving Brazilian soybeans and the Chinese manufacturing sector was the best scenario for the Chinese economy, once it presented the best indices for the latter.    

10.	 DALLEMOLE, Dilamar; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; SILVA, G. E.. 2018.
O PERFIL DO CONSUMIDOR E O MERCADO DE SEGURO AUTO DE CUIABÁ, BRASIL In Proceedings of the 25th APDR Congress 25th APDR Congress Lisboa, Portugal 2018 25 81-90 Angra do Heroísmo, Portugal: Associação Portuguesa para o Desenvolvimento Regional - APDR
Palavras-chave: seguro auto, Perfil do Consumidor, mercado, Cuiabá
Áreas do conhecimento: Economia Regional
Setores de atividade: Seguros, resseguros, previdência complementar e planos de saúde, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://apdr.pt/data/documents/PROCEEDINGS_APDRCongress2018.pdf]    

11.	 TOLDI, K.; FROZZA, F.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; BARI, M. L.. 2017.
A EVOLUÇÃO DA AGROPECUÁRIA E DA AGROINDÚSTRIA BRASILEIRA: UM COMPARATIVO DA MATRIZ INSUMO-PRODUTO 2003 E 2013 In Inovação, Extensão e Cooperação para o Desenvolvimento 55º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÂO E SOCIOLOGIA RURAL Santa Maria-RS 2017 55 1-20 Brasilia: SOBER
Palavras-chave: Matriz insumo-produto, indicadores econômicos, agropecuária
Áreas do conhecimento: Economia Agrária,Economia Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.7/7973.pdf]
A agropecuária e a agroindústria brasileira passaram por modificações ao longo do tempo, essas mudanças impactaram na economia. Diante disso, o objetivo deste estudo foi verificar a evolução da agropecuária e da agroindústria a partir dos indicadores das matrizes de insumo-produto de 2003 e 2013. Para a análise foram utilizados os multiplicadores de produção, de emprego, de renda, de importações e de impostos, além dos índices de encadeamentos para frente e para trás das atividades avaliadas. Apesar das oscilações apresentadas durantes os 10 anos, as atividades não sofreram grandes mudanças nos encadeamentos. Notou-se um decrescimento do impacto econômico do emprego que sugere relação com a mecanização e aumentos de salários, lucro, impostos, importações e exportações. Já os multiplicadores em média tiveram decrescimento, apenas o lucro teve incremento. Evidenciou-se que o setor de alimentos e bebidas possui os maiores multiplicadores. As atividades de alimentos e bebidas, celulose e produtos de papel e têxteis indicaram-se como setores chaves na economia brasileira em 2003. Já em 2013 o setor têxtil perdeu competitividade no encadeamento para frente. Conclui-se, que não houve avanços significativos na agropecuária e na agroindústria ao longo dos 10 anos.    

12.	 BROCANELLI, G. R. R.; FERRAZ, V. A. C.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2017.
ANÁLISE DOS FATORES DE CRESCIMENTO DAS RECEITAS DE EXPORTAÇÕES BRASILEIRAS DO SUCO DE LARANJA: 1997-2015 In Inovação, Extensão e Cooperação para o Desenvolvimento 55º CONGRESSO DA SOCIEDADE BRASILEIRA DE ECONOMIA, ADMINISTRAÇÂO E SOCIOLOGIA RURAL Santa Maria - RS 2017 55 1-20 Brasilia: SOBER
Palavras-chave: taxa de câmbio, shift-share, commodity
Áreas do conhecimento: Economia Agrária,Economia Internacional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital
Neste artigo são analisadas a taxa de câmbio, a quantidade exportada e o preço internacional do suco de laranja sobre a receita da exportação brasileira dessa commodity, no período de 1997 a 2015. A análise foi feita através do método shift-share, que permite decompor o efeito isolado das variáveis estudadas sobre a referida receita. Os resultados apontaram que as receitas das exportações de suco de laranja são cíclicas. O câmbio se mostrou o grande influenciador, seguido pelo preço, que também afetou de forma concisa nas receitas. Palavras-chave: taxa de câmbio, shift-share, commodity    

13.	 AZEVEDO, D. B.; GIORDANI, A. M.; FIGUEIREDO, Adriano M.R; LOPES, J. C. J.. 2016.
CADEIA PRODUTIVA DE UMA COOPERATIVA DE PRODUÇÃO ORGÂNICA DE CAMPO GRANDE – MS In Desenvolvimento, território e biodiversidade 54º Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural: Maceio-AL 2016 54 1-17 Maceio-AL: SOBER/UFAL
Palavras-chave: Cooperativismo, Produtos Orgânicos, Cadeia produtiva
Áreas do conhecimento: Economia Agrária,Administração da Produção
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.6/1/6886.pdf]
A preocupação ambiental avança para a gestão das Cooperativas, uma vez que elas fazem parte das cadeias produtivas. Este artigo busca analisar a cadeia produtiva de produtos orgânicos de uma Cooperativa. Para isso foram coletadas informações sobre sua história, por meio de entrevista, e obtidos dados referentes ao funcionamento da mesma, por meio de questionário aplicado aos produtores. O modo de produção orgânico contribui, em níveis específicos e segundo particularidades de casos, com uma melhoria no nível do bem-estar da população. Como resultado verificou que há contribuições positivas ao meio ambiente, à saúde humana, à renda das famílias, emprego, saúde e segurança do trabalhador rural, e com isso diminui o nível de miséria e desemprego. Dentre os resultados para além da produção, observou-se um perfil comum aos produtores orgânicos cooperados. Verificaram-se características peculiares à produção da Cooperativa deste estudo e uma complexidade na cadeia produtiva na qual ela está inserida, propiciando assim outros desdobramentos em futuras pesquisas    

14.	 TEIXEIRA, M. D. J.; FIGUEIREDO, Adriano M.R. 2015.
ANÁLISE INTERSETORIAL E ESPACIAL DOS SETORES DA CADEIA PRODUTIVA DE MADEIRA E MÓVEIS NA ECONOMIA DE MATO GROSSO In Agropecuária, Meio Ambiente e Desenvolvimento 53º Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural João Pessoa-PB 2015 53 1-20 João Pessoa-PB: SOBER/UFPB
Palavras-chave: Cadeia Produtiva da Madeira, Arranjo Produtivo Local, Matriz insumo-produto
Áreas do conhecimento: Economia Regional,Métodos e Técnicas do Planejamento Urbano e Regional,Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.5/1/4235.pdf]
Diante do crescimento do setor moveleiro de Mato Grosso, principalmente no tocante aos empregos, este artigo objetivou mensurar o impacto que o setor possui na economia do estado, assim como identificar as atividades da cadeia produtiva da madeira mais representativas em seus municípios, abrangendo atividades de produção florestal e atividades industriais ligadas ao processamento da madeira desde o desdobramento da matéria-prima até a fabricação de materiais que a utilizam como insumo e o setor de comércio de madeira. Por fim, foram identificadas as ligações causadas pelas atividades citadas anteriormente nos demais setores da economia por meio dos efeitos multiplicadores gerados a partir da Matriz de Insumo Produto. O mapeamento dos municípios especializados foi realizado por meio do Índice de Concentração Normalizado (ICn). Os resultados demonstram que o estado vem crescendo neste setor, no entanto, algumas atividades como fabricação de móveis e comércio de bens finais precisam de maior desenvolvimento para se equiparar com as demais. Verificou-se a concentração de municípios especializados nas atividades do setor moveleiro na região Norte do estado. Constatou-se que o setor de “madeira e mobiliário” é considerado “chave”, pois promove rendimentos crescentes de escala e possui expressivo efeito multiplicador para o estado. Assim, sugere-se implantar estudos para aprimorar e agregar valor às atividades da cadeia produtiva da madeira no estado, tendo em vista sua relevância para o desenvolvimento regional.    

15.	 FAGUNDES, M. B. B.; DIAS, D. T.; FIGUEIREDO NETO, L. F.; FIGUEIREDO, Adriano M.R; TREDEZINI, C. A. O.. 2015.
COMPOSIÇÃO DE PRODUTO, DEMANDA, RENDIMENTO E RELAÇÕES INTER SETORIAIS DA AGROPECUÁRIA DE MATO GROSSO DO SUL In Agropecuária, Meio Ambiente e Desenvolvimento 53º Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural João Pessoa-PB 2015 53 1-18 João Pessoa-PB: UFPB/SOBER
Palavras-chave: agropecuária, consumo intermediário, produto, despesas, remuneração
Áreas do conhecimento: Economia Regional,Economia Agrária,Métodos e Técnicas do Planejamento Urbano e Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.5/1/5639.pdf]
O objetivo geral deste artigo consiste em caracterizar a composição de produto, demanda, rendimento e das relações Inter Setoriais da agropecuária de Mato Grosso do Sul. Uma vez que o PIB da atividade do Estado contribui significativamente com o PIB da economia, ao exercer efeitos multiplicadores sobre os diversos setores. Diante disso, utilizou-se para tanto o método quantitativo de pesquisa, descrito na matriz-insumo-produto finalizada em março de 2015 e que traduziu de forma mais atualizada a dinâmica da agropecuária nas compras e vendas de insumos e, na composição do PIB pelas óticas do produto, rendimento e despesa. Dentre os principais resultados auferidos estão as compras e vendas concentradas, principalmente, do próprio setor, de alimentos e bebidas. Quanto as óticas do PIB, pela produção o setor se posicionou em quarto e quinto, diante da divisão da agropecuária em dois grupos: agricultura, silvicultura e exploração e, pecuária e pesca. Sobre o rendimento, as tributações e salários da agropecuária atingiram pequenas proporções sobre a economia total. Por fim pela despesa, o destaque coube a participação superior a 50% das exportações destinadas ao restante do Brasil.    

16.	   SILVA, C. E. S. F.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; PEREIRA, M. W. G.. 2015.
Efeitos de um acordo bilateral entre Brasil e China na economia do Centro-Oeste: uma abordagem de equilíbrio geral computável In Anais do Encontro Nacional da ABER Encontro Nacional da Associação Brasileira de Estudos Regionais e Urbanos Curitiba-PR 2015 13 1-20 Curitiba-PR: ABER
Palavras-chave: Acordo Brasil-China, Centro-Oeste, PAEG
Áreas do conhecimento: Economia Regional,Métodos e Técnicas do Planejamento Urbano e Regional,Relações do Comércio; Política Comercial; Integração Econômica
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://www.brsa.org.br/fotos/artigo1-2015-06-08-20-10-54.docx]
   

17.	 LISBOA, E. A. S.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; RAUSCHKOLB, A. S.. 2014.
A AGROINDÚSTRIA CANAVIEIRA MATO-GROSSENSE E O SISTEMA DE GESTÃO AMBIENTAL In Anais do 52º Congresso da SOBER 2014 52º Congresso da SOBER 2014 Goiânia-GO 2014 52 1-14 Brasília-DF: SOBER
Palavras-chave: gestão ambiental, desenvolvimento sustentável, setor sucroalcooleiro
Áreas do conhecimento: Economia dos Recursos Naturais,Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.4/1/3099.pdf]
A pesquisa foi elaborada com o objetivo de investigar a atual situação do Estado de Mato Grosso quanto à disposição do setor sucroalcooleiro em produzir de acordo com a correta gestão e aproveitamento dos resíduos gerados no processo produtivo. O problema central se concentrou em saber de que modo ocorre e quais as motivações para que haja a gestão de resíduos ambientais na indústria sucroalcooleira de Mato Grosso. Dentre os métodos e procedimentos utilizados na pesquisa, fez-se pesquisa de campo com aplicação de questionários junto a três agroindústrias do setor sucroalcooleiro no estado. Como principais resultados destacam-se a ineficiência dos sistemas de gestão ambiental instalados nas agroindústrias analisadas e pouca participação governamental no processo de formulação de políticas públicas ambientais bem como a ineficiência da fiscalização.    

18.	 SANTOS, C. D.; NASCIMENTO, A. P.; MARCHIORO, L. W.; BARI, M. L.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2014.
CONCENTRAÇÃO ESPACIAL DA PRODUÇÃO BOVINA: UM ESTUDO NO ESTADO DE MATO GROSSO NO ANO DE 2012 In Anais do 52º Congresso da SOBER 2014 52º Congresso da SOBER 2014 Goiânia-GO 2014 52 1-20 Brasília-DF: SOBER
Palavras-chave: concentracao, Mato Grosso, Economia Regional
Áreas do conhecimento: Economia Agrária,Economia Regional,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.4/1/3097.pdf]
O presente trabalho teve como objetivo geral, identificar como está concentrado espacialmente o efetivo bovino de Mato Grosso, de acordo com a classificação das categorias: machos e fêmeas, subdivididos em bezerros e bezerras até um ano; novilhas e novilhos de um a três anos; vacas, bois ou touros acima de três anos nos municípios do Estado. A base de dados utilizada foi a do Instituto de Defesa Agropecuária INDEA-MT, com o cálculo do Índice de Concentração Normalizado (ICN) cuja composição considera três outros índices: o Quociente Locacional (QL), o Índice de concentração de Hirschman-Herfindahl (IHH) e a Participação Relativa (PR). Verificou-se com o estudo que a bovinocultura mato-grossense encontra-se em expansão em todo o território. Porém alguns municípios se destacaram ao apresentar o ICN um pouco mais elevado que os demais, mas, não apresentando variações significativas que determinasse a concentração de alguma categoria bovina no Estado.    

19.	 CANGUSSU, S. A. V.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; MAGALHAES, L. A. F.. 2014.
CONSTRUÇÃO DA MATRIZ DE CONTABILIDADE SOCIAL DE MATO GROSSO, ANO BASE 2007 In Anais do 52º Congresso da SOBER 2014 52º Congresso da SOBER 2014 Goiânia-GO 2014 52 1-20 Brasília-DF: SOBER
Palavras-chave: Matriz de Contabilidade Social, Mato Grosso, multiplicadores
Áreas do conhecimento: Economia Agrária,Economia Regional,Métodos e Técnicas do Planejamento Urbano e Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.4/1/3773.pdf]
Este artigo apresenta a primeira tentativa de construção de uma Matriz de Contabilidade Social (MCS) regional para Mato Grosso. A matriz estimada é para o ano base 2007, em sua origem com 196 contas, sendo 78 atividades, 110 produtos, dois fatores de produção (firmas e trabalho), 1 classes de rendimento familiar, duas esferas governamentais ( Estadual e Federal), conta capital, resto do Brasil e resto do mundo. A elaboração da MCS foi iniciada a partir da Matriz Insumo-Produto de Mato Grosso-2007. Em seguida, outras informações foram agregadas para contemplar a estrutura de uma Matriz de Contabilidade Social regional. O resultado foi uma Matriz de Contabilidade Social agregada em 11 setores (atividades e produtos), mais trabalho, firmas, famílias, governo estadual, governo federal, capital, resto do Brasil e resto do mundo. Finalizando, calcularam-se os multiplicadores contábeis, que foram utilizados para estimar a relação entre os setores econômicos de Mato Grosso.    

20.	 NASCIMENTO, A. P.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; RODRIGUES, P. M.; MARCHIORO, L. W.. 2014.
Decomposição e análise da variação do valor da produção de arroz no estado de Mato Grosso In Anais do 52º Congresso da SOBER 2014 52º Congresso da SOBER 2014 Goiânia-GO 2014 52 1-13 Brasília-DF: SOBER
Palavras-chave: arroz, valor da produção, shift-share
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Economia Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.4/1/2834.pdf]
No presente estudo, buscou-se analisar o valor da produção de arroz no estado de Mato Grosso no período de 1994 a 2012, através do modelo shift share, onde foi possível verificar quais os efeitos (área, rendimento e preço) que influenciaram no seu acréscimo ou declínio. Constatou-se que inicialmente o valor da produção apresenta taxas anuais de crescimento negativas e expressivas em 1995, 2001, 2005 e 2006 devidas, principalmente, aos efeitos preço e área. Em 1999 e 2004, as taxas positivas que se apresentaram mais significativas ocorreram devido ao efeito área (99,5% e 67,9%, respectivamente). Observa-se que nos últimos anos o valor da produção de arroz vem apresentando declínio, devido à diminuição da produção, motivada pela perda e restrições de abertura de novas áreas, e à competição com outras culturas como a soja e o milho, as quais possuem melhor comercialização. Um dos determinantes que vem contribuindo para esse decrescimento da orizicultura no estado é o custo de produção deste cereal, tornando o arroz menos competitivo em relação a essas culturas.    

21.	 MAGALHAES, L. A. F.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; CANGUSSU, S. A. V.. 2014.
EFEITOS DA ALTERAÇÃO NA TRIBUTAÇÃO SOBRE OS SETORES DA ECONOMIA DE MATO GROSSO: UMA ABORDAGEM DE MATRIZ DE CONTABILIDADE SOCIAL In Anais do 52º Congresso da SOBER 2014 52º Congresso da SOBER 2014 Goiânia-GO 2014 52 1-19 Brasília-DF: SOBER
Palavras-chave: Política fiscal, Matriz de Contabilidade Social, Análise de multiplicadores
Áreas do conhecimento: Economia Agrária,Economia Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Administração pública, defesa e seguridade social
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/tra/arquivos/ser.4/1/3439.pdf]
O presente trabalho procura subsidiar os tomadores de decisão de políticas públicas com informações (mensuração dos impactos) que possibilitem ilustrar e analisar os impactos econômicos da redução do valor pago em tributos estaduais pelos setores econômicos do estado de Mato Grosso. O método utilizado para o alcance dos objetivos propostos foi o de multiplicadores da Matriz de Contabilidade Social, que mensuram os efeitos econômicos de alterações na demanda final de contas consideradas exógenas. A análise dos multiplicadores da Matriz de Contabilidade Social demonstrou que uma política fiscal que proponha a redução da tributação num valor de 10% nos setores Agropecuário, Agroindústrias e Outros serviços, resultaria, entre outros efeitos, num aumento da demanda total no valor de 4.854,17 milhões de reais.    

22.	 LISBOA, E. A. S.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2013.
A economia florestal do estado de Mato Grosso, Brasil: uma análise de insumo-produto In Anais do 51º Congresso da SOBER 2013 51º Congresso da SOBER 2013 Belém-PA 2013 51 1-13 Brasília-DF: SOBER
Palavras-chave: MIP, Extrativismo, Madeira
Áreas do conhecimento: Economia Agrária,Economia Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Fabricação de produtos de madeira, Fabricação de móveis
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/useradm/anais/?clt=ser.3]
Este trabalho identificou os impactos que a atividade florestal gera na produção, na renda, nos empregos e nos salários da economia de Mato Grosso. Com base no arcabouço teórico de insumo-produto, e com dados de 2007, discutem-se os índices de ligação de Rasmussen Hirschman, os índices puros de ligação e os multiplicadores de impostos, lucro e importações. Somente a atividade correspondente a produção de papel e celulose é considerada chave no encadeamento de Rasmussen-Hirschman, mas com efeito inexpressivo na economia quando se olham os índices puros. Entretanto, todos os setores mostram-se mais encadeados se comparados à situação de 1999. Os multiplicadores foram mais expressivos para celulose e papel, mas é a atividade de silvicultura que gera os maiores impactos econômicos entre os três setores estudados.    

23.	 OLIVEIRA, L. J.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; RODRIGUES, P. M.; RAUSCHKOLB, A. S.. 2013.
Análise das transações e da governança do setor apícola na região norte de Mato Grosso In Anais do 51º Congresso da SOBER 2013 51º Congresso da SOBER 2013 Belém-PA 2013 51 1-15 Brasília-DF: SOBER
Palavras-chave: governança, transacao, apicultura
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/useradm/anais/?clt=ser.3]
Nesse estudo buscou-se analisar a estrutura de governança do setor apícola na região Norte de Mato Grosso caracterizando os tipos de transações dos apicultores da região. A base teórica foi fundamentada na Nova Economia Institucional (NEI), porém utilizou-se também de algumas considerações dos modos de coordenação em função dos níveis garantias abordado pela Economia das Convenções. Na elaboração deste trabalho fez-se o uso de dados primários através de uma pesquisa de campo feita no Norte de Mato Grosso. Os dados foram obtidos pela aplicação de 52 questionários junto aos apicultores da região. Verificou-se que a estrutura de governança dos apicultores da região Norte de Mato Grosso é predominantemente via “Mercado Spot”. Esse modo de coordenação vem favorecendo o desenvolvimento da atividade no contexto vivenciado pelos apicultores locais. O preço de mercado vigente, praticado na região, demonstrou ser mais atrativo para os produtores do que aqueles estipulados por meio de acordos contratuais com garantia fraca. Pôde-se concluir também que não só os atributos das transações, mas fatores como a informalidade da atividade (a falta dos selos dos Serviços de Inspeção Federal, Estadual e Municipal) e o problema da produção em escala também influenciam nas transações e consequentemente afetam a estrutura de governança local.    

24.	 OLIVEIRA, L. J.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; RAUSCHKOLB, A. S.; RODRIGUES, P. M.. 2013.
Análise do perfil dos produtores apícolas da região norte do estado de Mato Grosso In Anais do 51º Congresso da SOBER 2013 51º Congresso da SOBER 2013 Belém-PA 2013 51 1-17 Brasília-DF: SOBER
Palavras-chave: apicultura, alfa de Cronbach , analise fatorial
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/useradm/anais/?clt=ser.3]
Analisa-se o perfil dos apicultores da região Nortede Mato Grosso através de um diagnóstico da apicultura local, destacando-se os principais fatores que caracterizam o perfil dos apicultores locais. Para a elaboração desse trabalho fez-se o uso de dados primários através de uma pesquisa de campo feita na região Norte do estado. Os dados foram obtidos pela aplicação de questionários e entrevistas através deuma amostra de 52 apicultores ligados ao desenvolvimento da apicultura na região. Os dados coletados foram submetidos à análise de confiabilidade Alfa de Cronbach e posteriormente utilizou-se a análise fatorial por componentes principais. Foram identificados sete fatores-chave que caracterizaram o perfil dos apicultores do Norte de Mato Grosso. O primeiro fator foi interpretado como sendo o “nível de especialização”. O segundo fator foi interpretado como um indicativo da “origem da renda”. O terceiro fator foi interpretado como o “modo de aquisição das colmeias”. O quarto fator foi interpretado como sendo o “nível de instrução com aperfeiçoamento”. O quinto fator foi interpretado como sendo as “associações”. O sexto fator foi interpretado como sendo o “nível de instrução sem aperfeiçoamento”. Por fim, o sétimo fator foi interpretado como sendo a “contribuição da apicultura na composição da renda familiar”. É importante frisar que a apicultura apresentou-se como uma atividade complementar de renda e de geração de trabalho para os produtores da região. O mel é o principal alimento produzido pelos produtores locais, sendo a grande maioria comercializada no mercado local, através das feiras livres e diretamente na unidade de produção.    

25.	 SILVA, C. E. S. F.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; SCHOENHERR, R. P.. 2013.
Efeitos dos investimentos públicos em infraestrutura para a Copa do Mundo FIFA 2014 no setor da construção em Mato Grosso In Anais do XI ENCONTRO NACIONAL DA ASSOCIAÇÃO BRASILEIRA DE ESTUDOS REGIONAIS E URBANOS - XI ENABER XI ENCONTRO NACIONAL DA ASSOCIAÇÃO BRASILEIRA DE ESTUDOS REGIONAIS E URBANOS - XI ENABER Foz do Iguaçu-PR 2013 11 1-14 Juiz de Fora-MG: ABER/UFJF
Palavras-chave: futebol, infraestrutura, construção
Áreas do conhecimento: Economia Regional e Urbana,Crescimento, Flutuações e Planejamento Econômico,Métodos e Técnicas do Planejamento Urbano e Regional
Setores de atividade: Administração pública, defesa e seguridade social, Serviços especializados para construção
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://iclips.no-ip.biz:8001/artigosaprovados/d344b0a2-ed13-4044-b447-087d4c684275.docx]
A cidade de Cuiabá será sede da Copa do Mundo FIFA 2014. Um importante evento esportivo de repercussão mundial, em que investimentos principalmente na área de infraestrutura se fazem necessários. Sendo o setor da construção o mais impactado diretamente pelo mundial. Neste trabalho procura-se verificar os impactos dos investimentos públicos em infraestrutura para a Copa do Mundo FIFA 2014 no setor da construção de Mato Grosso. Também procurou-se demonstrar o papel da construção para a economia do estado. Para tal, utilizou-se como base a Matriz de Insumo-Produto Inter-Regional de Mato Grosso e Resto do Brasil – 2007 e os dados das obras públicas da SECOPA/MT (Secretaria Extraordinária da Copa Mundo FIFA 2014), órgão responsável pelos assuntos da Copa do Mundo no estado de Mato Grosso. O método utilizado neste estudo foi o dos multiplicadores de impacto e o choque na demanda final. Os multiplicadores mostraram o quanto é impactado na economia como um todo através de uma mudança exógena na demanda final no setor de construção. Os resultados do impacto na demanda final evidenciaram que os investimentos públicos em infraestrutura para a Copa do Mundo em Cuiabá terão um impacto no setor da construção de Mato Grosso de 6,17% do PIB.    

26.	 ROSA, M. J. A.; CANGUSSU, S. A. V.; REINHOLD, A. K.; BARI, M. L.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES. 2013.
Fonte de crescimento da produção da soja em Mato Grosso a partir do modelo shift-share In Anais do 51º Congresso da SOBER 2013 51º Congresso da SOBER 2013 Belém-PA 2013 51 1-19 Brasília-DF: SOBER
Palavras-chave: soja, shift-share, Mato Grosso
Áreas do conhecimento: Economia Regional,Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://icongresso.itarget.com.br/useradm/anais/?clt=ser.3]
A proposta deste trabalho é analisar a dinâmica de crescimento da produção da soja no estado de Mato Grosso como um todo e por macrorregiões de acordo com a classificação do Instituto Mato-grossense de Economia e Agropecuária (IMEA), a partir da utilização do método Shift-Share, no período 1990 a 2011. Os resultados apresentados indicam que existem diferenças nos fatores que determinam o crescimento da produção de soja na região mato-grossense. No geral foi possível verificar que houve mudanças na localização da produção da década de 1990 para a década do ano 2000. De modo geral, no estado de Mato Grosso, os fatores explicativos para o crescimento da produção de soja foi o efeito área o que mais influenciou na mudança e ampliação da produção de soja no estado, seguida pelo efeito rendimento e outros efeitos.    

27.	 OLIVEIRA, L. J.; FIGUEIREDO, ADRIANO MARCOS RODRIGUES; RODRIGUES, P. M.; RAUSCHKOLB, A. S.. 2013.
O ambiente institucional e organizacional do setor apícola na região norte de Mato Grosso In Anais do 51º Congresso da SOBER 2013 51º Congresso da SOBER 2013 Belém-PA 2013 51 1-20 Brasília-DF: SOBER
Palavras-chave: instituições, organizações, apicultura
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital
Verificou-se no presente trabalho que no ambiente institucional, são feitas análises da qualidade do mel comercializado na região e também são ofertados cursos e palestras de boas práticas de higiene, mantendo assim um controle de segurança no padrão de qualidade do mel natural. Com relação às organizações envolvidas na atividade, a maioria atua na capacitação e qualificação dos apicultores, principalmente por cursos e consultorias disponibilizadas pelo SEBRAE, que foi apontado como a empresa “motriz” na articulação da atividade na região. Porém, ressalta-se que as ações são desenvolvidas coletivamente entre produtores e instituições por meio de assembleias e/ou reuniões. Por fim, algumas limitações ao desenvolvimento da apicultura local foram apontadas no decorrer desse trabalho, entre elas as principais podem estar atribuídas à falta de uma política específica na atividade, principalmente de crédito e/ou fomento. A infraestrutura física e humana é precária na região, visto que não há profissionais com formação técnica específica para atuar na atividade. Apesar disso, há uma tendência de que se aumente o poder de barganha dos apicultores na região por intermédio da Cooperativa dos Apicultores do Norte de Mato Grosso (COAPISNORTE) que está em fase de consolidação na região. Isso faz com que os produtores agreguem mais valor ao produto comercializado, aumentando assim, o desempenho competitivo na estrutura produtiva, propiciando o desenvolvimento da atividade de forma justa, econômica e sustentável.    

28.	 OLIVEIRA, L. J.; FIGUEIREDO, A. M. R.. 2012.
Análise das Transações e da Estrutura de Governança no Setor Apícola: o Caso da APISNORTE no Estado de Mato Grosso In Anais do 50º Congresso da SOBER 2012 50º Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural - SOBER Vitoria-ES 2012 1 1-1 Brasilia-DF: SOBER/UFES
Palavras-chave: estrutura de governança, apicultura, mercados
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://www.itarget.com.br/newclients/sober.org.br/congresso2012/]
Analisa-se o funcionamento produtivo do setor apícola da Associação dos Apicultores do Norte do Estado de Mato Grosso (APISNORTE) e suas relações comerciais com base teórica da Nova Economia Institucional (NEI). Identificam-se as diferentes formas contratuais enquanto estruturas de governança dessas transações. A análise sugere mudanças significativas nas formas organizacionais do setor apícola, no caso dos agentes que fazem parte da APISNORTE. Houve pouca centralidade da APISNORTE na coordenação e organização da cadeia produtiva. Identificou-se que a forma de transação é efetuada através de governança do tipo mercado Spot (transação ocorre em um único instante de tempo). Neste sentido, os mecanismos mais elaborados como o mercado a termo ou qualquer outra forma de governança ainda são pouco ou nunca utilizados pelos produtores apícolas da APISNORTE.    

29.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.; TEIXEIRA, E. C.; GURGEL, A. C.. 2012.
Análise de Barreiras não Tarifárias Sobre a Soja e a Carne Brasileiras In Anais do 50º Congresso da SOBER 2012 50º Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural - SOBER Vitoria-ES 2012 1 1-1 Brasilia-DF: SOBER/UFES
Palavras-chave: embargo, PAEG, MPSGE, carne, soja
Áreas do conhecimento: Economia Agrária,Economia Regional,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://www.itarget.com.br/newclients/sober.org.br/congresso2012/]
Os fluxos comerciais brasileiros aumentaram nos últimos anos, mesmo com altas tarifas e barreiras comerciais não-tarifárias. Algumas barreiras não-tarifárias incluem SPS (medidas sanitárias e fitossanitárias). Nos últimos dez anos, a China impôs um embargo à soja brasileira, bem como a União Europeia e os EUA, sobre a carne bovina brasileira. Avaliam-se os efeitos do embargo imposto à carne brasileira e à soja. Especificamente analisa-se o comércio regional brasileiro e seus principais indicadores, como a produção, os preços das commodities e fatores, PIB, e bem-estar. O modelo analítico é baseado em um modelo de equilíbrio geral computável chamado PAEG. O pacote PAEG permite a análise das regiões brasileiras, as suas relações com outros países ou blocos econômicos e, até mesmo, relações transversais entre todas as regiões / países. O PAEG utiliza o banco de dados na versão 7 do GTAP associado com a desagregação regional brasileira com 2 fatores primários, 19 setores e 12 regiões (incluindo 5 regiões brasileiras). Simulam-se três cenários: embargo chinês à importação de soja brasileira; embargo da União Europeia (UE) à carne brasileira, e embargo americano à carne brasileira. Simula-se a aplicação de uma tarifa de importação proibitiva (EMTr) pela China, União Européia e os EUA. Os resultados mostram que o embargo chinês sobre a soja brasileira levaria a uma diminuição do consumo de soja na China de cerca de USD 750 milhões. Em relação às regiões brasileiras ocorreu redução nas exportações (-USD 250 milhões) no Centro-Oeste, mas aumentou as exportações da região Sudeste (USD 690 milhões), principalmente de produtos manufaturados e roupas. Quanto aos embargos da UE e dos EUA à carne brasileira, observa-se que os impactos são menores do que os resultantes do embargo chinês sobre a soja brasileira. O embargo americano causaria mais danos do que o europeu. Os EUA enfrentariam perdas de bem-estar, tornando-se mais sensível do que a União Europeia, em relação à carne brasileira.   

30.	 OLIVEIRA, L. J.; RAUSCHKOLB, A. S.; BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.. 2012.
Análise dos setores de Criação de Bovinos Leiteiros e Indústria de Laticínios na economia de Mato Grosso com enfoque de Insumo Produto In Anais do 50º Congresso da SOBER 2012 50º Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural - SOBER Vitoria-ES 2012 1 1-1 Brasilia-DF: SOBER-UFES
Palavras-chave: Agronegócio, leite, lácteos
Áreas do conhecimento: Economia Agrária,Economia Regional,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://www.itarget.com.br/newclients/sober.org.br/congresso2012/]
O objetivo deste estudo foi examinar os impactos na economia de Mato Grosso dos setores de criação de bovinos e indústria de laticínios. Baseia-se nas técnicas e conceitos de insumo-produto, a partir da matriz insumo-produto do estado de Mato Grosso ano de 2007. Realizou-se a análise dos índices de ligação de Rasmussen-Hirschman, índices puros de ligação, os multiplicadores tipo I e II de produto, renda e emprego, os multiplicadores de impostos, lucro e importação. Os resultados revelam que o setor de criação de bovinos de leite é chave para frente e para trás, enquanto o setor de indústria de laticínios em questão é chave somente para trás, ou seja, impacta mais os setores a montante que à jusante da cadeia. Os resultados obtidos indicam que um investimento no setor de criação de bovinos leiteiros gerará mais benefícios à economia de Mato Grosso do que o mesmo investimento no setor de indústria de laticínios, ocasionando um aumento maior na renda e emprego, tanto direta, como indireta e de modo induzido.    

31.	 RAUSCHKOLB, A. S.; OLIVEIRA, L. J.; FIGUEIREDO, Adriano M.R. 2012.
Efeitos multiplicadores de insumo produto dos setores de criação e abate de frangos no estado de Mato Grosso In Anais do ... Encontro Nacional da Associação Brasileira de Estudos Regionais e Urbanos X Encontro Nacional da Associação Brasileira de Estudos Regionais e Urbanos Recife, PE 2012 10 1-14 Recife, PE: Associação Brasileira de Estudos Regionais e Urbanos
Palavras-chave: Agronegócio, frango, avicultura
Áreas do conhecimento: Economia Agrária,Economia Regional
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://200.251.138.109:8001/artigosaprovados/4ff12503-92dd-4759-800c-949fc7518be5.pdf]
A atividade avícola no estado de Mato Grosso tem grande importância para o desenvolvimento da economia local. O detalhamento das ligações setoriais na economia permite melhor visualização desta relação. Assim, esse trabalho objetivou analisar os impactos dos setores de criação de aves e abate de frangos na economia mato-grossense. Baseou-se nas técnicas e conceitos de insumo-produto a partir da matriz estadual de 2007. Realizou-se a análise dos índices de ligação de Rasmussen-Hirschman, dos índices puros de ligação, dos multiplicadores tipo I e II de produto, renda e emprego, e dos multiplicadores de impostos, lucro e importação. Os resultados revelam que os setores em questão são chaves somente para trás, e impactam mais os setores a montante que à jusante da cadeia. Verificou-se ainda que um investimento no setor de criação de aves gerará mais benefícios à economia de Mato Grosso do que o mesmo investimento no setor de abate de frangos, ocasionando um aumento maior na renda, emprego e valor da produção, tanto de forma direta, indireta bem como induzida.    

32.	 FIGUEIREDO, A. M. R.; BONJOUR, S. C. M.; GURGEL, A. C.; TEIXEIRA, E. C.. 2012.
Impactos Econômicos de Melhorias no Transporte nas Macrorregiões Brasileiras In Anais do 50º Congresso da SOBER 2012 50º Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural - SOBER Vitoria-ES 2012 1 1-1 Brasilia-DF: SOBER/UFES
Palavras-chave: Equilíbrio geral, PAEG, MPSGE
Áreas do conhecimento: Economia Agrária,Economia Regional,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária e Serviços Relacionados, Transporte terrestre
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://www.itarget.com.br/newclients/sober.org.br/congresso2012/]
O Plano Nacional de Logística e Transportes do Brasil indica investimento em diferentes modalidades de transporte e em todo o país até 2023. Estes são investimentos em cerca de 9.000 km de ferrovias, trens de alta velocidade e outros projetos que alteram a proporção do modal do transporte ferroviário dos 25% atuais para 35%. Para analisar os impactos da mudança da infraestrutura, o pacote analítico do Projeto de Análise de Equilíbrio Geral da Economia Brasileira (PAEG) é usado. O modelo do PAEG permite a análise das macrorregiões brasileiras, as suas relações com outros países ou blocos econômicos e as relações multissetoriais entre todas as regiões ou países. Assim, investigam-se os efeitos econômicos das melhorias na infraestrutura de transporte nas macrorregiões brasileiras. O crescimento do PIB é acompanhado de crescimento nos gastos do governo, dos investimentos e das exportações, com exceção do investimento e exportações da região Norte. O consumo privado reduz e transmite o efeito negativo ao bem-estar das famílias. Os fluxos comerciais são aumentados entre as regiões brasileiras, bem como entre os países, indicando maior integração comercial. Os preços reais dos fatores aumentam em todas as regiões e os preços reais ao consumidor reduzem no Sul e Sudeste. Os preços dos serviços de transporte diminuem em média 18% nas regiões brasileiras.    

33.	 OLIVEIRA, J.; FIGUEIREDO, A. M. R.; CARVALHO, R. C.. 2011.
A evolução das exportações e da competitividade da carne bovina brasileira no período de 1997 a 2007 In Anais do 49 Congresso da SOBER XLIX Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural Belo Horizonte-MG 2011 49 1-1 Belo Horizonte-MG: FACE-UFMG/SOBER
Palavras-chave: carne bovina, competitividade, exportacao, market share, shift share
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Relações do Comércio; Política Comercial; Integração Econômica
Setores de atividade: Agricultura, Pecuária, Produção Florestal, Pesca e Aqüicultura
Referências adicionais: Brasil/Português. Meio de divulgação: Meio magnético. Home page: [http://www.sober.org.br]
As exportações de carne bovina do Brasil têm apresentado resultados promissores nos últimos anos, assumindo papel importante no mercado exportador brasileiro. O artigo analisa a evolução das exportações de carne bovina brasileira, bem como sua competitividade no período de 1997 a 2007, fazendo uma comparação com os principais países exportadores deste produto, ou seja, a Austrália, a Argentina e os Estados Unidos. Os procedimentos metodológicos são descritos a seguir: primeiramente foi utilizado o Índice Market Share (IMS) para verificar a parcela de mercado de cada um desses países; em segundo lugar efetuou-se os cálculos para o Modelo Constant Market Share com o objetivo de decompor as taxas de crescimento das exportações de carne dos países já citados. Por fim, para decompor os efeitos do crescimento das exportações brasileiras utilizou-se o Modelo Shift Share. Os resultados demonstraram que o Brasil, juntamente com a Austrália possuem as maiores parcelas de mercado de carne bovina, o Brasil apresentou destaque no efeito destino das exportações, a Austrália e os Estados Unidos destacaram-se no efeito Competitividade e a Argentina no efeito crescimento do comércio. Com o modelo Shift Share foi possível verificar que o aumento das receitas de exportações brasileiras teve maior influência no seu efeito total em virtude do efeito-quantidade.    

34.	 BONJOUR, S. C. M.; MUCELLINI, A. B.; FIGUEIREDO, A. M. R.. 2011.
As exportações de carne bovina e o nível de emprego da indústria frigorífica de Mato Grosso: uma análise econométrica utilizando o modelo ARMA In 49 Congresso da SOBER XLIX Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural Belo Horizonte-MG 2011 49 1-1 Belo Horizonte-MG: FACE-UFMG/SOBER
Palavras-chave: exportacao, carne bovina, Modelo ARMA
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Relações do Comércio; Política Comercial; Integração Econômica
Setores de atividade: Agricultura, Pecuária, Produção Florestal, Pesca e Aqüicultura
Referências adicionais: Brasil/Português. Meio de divulgação: Meio magnético. Home page: [http://www.sober.org.br]
Este artigo investiga a relação entre o efeito do comércio internacional sobre o mercado de trabalho, principalmente a percepção do efeito da globalização sobre o emprego O objetivo geral deste trabalho é estudar as relações entre o comércio internacional da carne bovina do estado de Mato Grosso e o mercado de trabalho da indústria frigorífica. Especificamente, investigar como as alterações do nível de emprego da indústria são explicadas pelas relações de comércio das exportações da carne bovina estadual. A mensuração desses efeitos foi realizada através de uma relação de causalidade entre essas duas variáveis, esperando que o nível de emprego da indústria fosse determinado pela demanda externa por carne, estimou-se um modelo econométrico auto-regressivo e de média móvel (ARMA) para especificar a relação de causa das exportações sobre o nível de emprego de acordo com os valores defasados e de termos de resíduos. Os resultados obtidos mostraram que as suposições da teoria de Kaldor acerca do crescimento industrial foram válidas, pois o nível de emprego estadual é induzido pela demanda de seus produtos.    

35.	 SARAIVA, M.B.; FIGUEIREDO, A. M. R.; GONTIJO, T. S.; GOMES, V.M.. 2011.
Determinantes do desenvolvimento rural dos municípios mato-grossenses In 49 Congresso da SOBER XLIX Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural Belo Horizonte-MG 2011 49 1-1 Belo Horizonte-MG: FACE-UFMG/SOBER
Palavras-chave: desenvolvimento agricola, analise fatorial, Mato Grosso
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Economia Regional e Urbana
Setores de atividade: Agricultura, Pecuária, Produção Florestal, Pesca e Aqüicultura
Referências adicionais: Brasil/Português. Meio de divulgação: Meio magnético. Home page: [http://www.sober.org.br]
O estado de Mato Grosso apresenta sua economia baseada em uma agricultura moderna e competitiva, entretanto ainda se exporta grande parte in natura. O processo de modernização da agricultura embora tenha aumentado a produtividade e, consequentemente, a competitividade da agricultura matogrossense, também gerou grande desigualdade de renda entre a população. O objetivo deste trabalho é mensurar e hierarquizar os municípios matogrossenses segundo seu Índice de Desenvolvimento Rural (IDR). Utilizou-se para análise, o método de Análise Fatorial. Os resultados evidenciaram que o IDR médio dos municípios encontra-se entorno de 60,48, na escala que vai de zero a cem. Deste total, 34% dos municípios apresentaram grau de desenvolvimento rural considera de nível médio ou superior e 66% avaliados como baixo ou inferior.    

36.	 PEREIRA, K.C.; FIGUEIREDO, A. M. R.; PEES, D.A.. 2011.
Governança e especificidade de ativos na reciclagem de embalagens de agrotóxicos em Mato Grosso In 49 Congresso da SOBER XLIX Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural Belo Horizonte-MG 2011 49 1-1 Belo Horizonte-MG: FACE-UFMT/SOBER
Palavras-chave: reciclagem, agrotoxicos, transacao, contratos, estrutura de governança
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais
Setores de atividade: Agricultura, Pecuária, Produção Florestal, Pesca e Aqüicultura, Indústrias de Transformação
Referências adicionais: Brasil/Português. Meio de divulgação: Meio magnético. Home page: [http://www.sober.org.br]
O processo de reciclagem de embalagens de agrotóxicos no Estado de Mato Grosso decorrente da aplicação herbicidas e pesticidas bem como seu controle nas atividades agropecuárias, tem se tornado um grande desafio para o governo e sociedade. Seu impacto sobre o meio ambiente vem levantando acaloradas discussões entre governo, comunidade científica e sociedade civil a respeito do destino final das embalagens de agrotóxicos, os limites do ecossistema e a necessidade de crescimento econômico. Com base nos conceitos teóricos da Nova Economia Institucional, os resultados mostram que as relações contratuais entre o INPEV e os seus parceiros, visa principalmente inibir a prática do oportunismo. Constatou-se ainda que, as máquinas utilizadas no processo de reciclagem de embalagens representam ativos dedicados à produção. Por sua vez, as embalagens de agrotóxicos seriam uma forma de ativo com especificidade física exigindo assim a elaboração de contratos com cláusulas contratuais específicas.    

37.	 SOUZA, S. S. S.; BONJOUR, S. C. M.; FIGUEIREDO, Adriano M.R. 2010.
Agronegócio em Mato Grosso: uma análise de indicadores de comércio exterior no período de 1997 a 2007 In Anales del II Congreso Internacional y IX Simposio de América Latina y el Caribe II Congreso Internacional y IX Simposio de América Latina y el Caribe Buenos Aires -Argentina 2010 2 1-1 Buenos Aires: CEINLADI-Universidad de Buenos Aires
Palavras-chave: vantagem competitiva, especializacao, Agronegócio, Mato Grosso
Áreas do conhecimento: Economia Agrária,Relações do Comércio; Política Comercial; Integração Econômica
Setores de atividade: Agricultura, Pecuária, Produção Florestal, Pesca e Aqüicultura
Referências adicionais: Argentina/Português. Meio de divulgação: Meio magnético
O objetivo geral deste trabalho é analisar a competitividade da agroindústria do estado de Mato Grosso, para o período de 1997-2007, bem como investigar a especialização da agroindústria no estado, detectando os pontos fortes e pontos fracos a partir dos indicadores Vantagem Comparativa Revelada, de Balassa e Taxa de Cobertura e também o índice de Contribuição ao Saldo Comercial para explicar a evolução dos diferentes produtos da agroindústria mato-grossense. O estado apresentou vantagem comparativa em alguns produtos como em sementes e frutos oleaginosos, gorduras, resíduos das indústrias alimentares. Setores como cereais, farinhas apresentaram competitividade após o ano de 2002. O índice de contribuição ao saldo comercial mostrou que o capítulo de sementes se destacou com valores positivos e superiores à unidade, demonstrando que este setor tem se configurado em um importante seguimento dentro da pauta de exportações de Mato Grosso. Pode-se verificar que os resultados obtidos com esse índice para esse capítulo foram semelhantes aos do índice de vantagem comparativa revelada (VCR). Procurou-se identificar os pontos fortes do agronegócio mato-grossense através dos resultados da vantagem comparativa revelada e da taxa de cobertura, sendo que a partir do ano de 1999 houve aumento de capítulos identificados como pontos fortes na economia do estado, e antes desse período, apenas o capítulo de sementes e o capítulo de produtos florestais foram considerados como pontos fortes. O destaque foi para o capítulo de produtos florestais que foi identificado como ponto forte em todo o período analisado. O capítulo de sementes foi considerado ponto forte em quase todo o período em estudo, mais precisamente nos anos de 1997-2003 e 2007, sendo que nos demais anos apresentou resultado neutro.    

38.	 BONJOUR, S. C. M.; FRANCO, C.; FIGUEIREDO, Adriano M.R. 2010.
Análise das transações e estruturas de governança na cadeia produtiva da avicultura de corte em Mato Grosso In Anais do XLVIII Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural XLVIII Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural Campo Grande-MS 2010 48 1-1 Brasilia DF: SOBER
Palavras-chave: estrutura de governança, Cadeia produtiva, analise das transacoes, avicultura de corte
Áreas do conhecimento: Economia Agrária,Organização Industrial e Estudos Industriais
Setores de atividade: Agricultura, Pecuária, Produção Florestal, Pesca e Aqüicultura
Referências adicionais: Brasil/Português. Meio de divulgação: Vários. Home page: [http://www.sober.org.br]
O setor da avicultura no Brasil tem sofrido profundas alterações, decorrentes principalmente de mudanças macroeconômicas, concorrenciais e de consumo no país. Dentre essas mudanças, pode-se destacar o estabelecimento de novas formas de transação entre produtores integrados e agroindústrias de abate e processamento. O presente trabalho analisou as transações e as estruturas de governança estabelecidas entre esses produtores de frango de corte e empresas agroindústrias de abate e processamento em Mato Grosso. Para tanto, os fundamentos teóricos da Nova Economia Institucional e da Economia dos Custos de Transação são utilizados como base. Foram utilizados dados secundários, bem como realizadas pesquisas de campo, junto a produtores integrados, agroindústrias de abate e processamento e agentes-chave. Identificou-se governança bilateral na relação entre produtores e frigoríficos e integração vertical na confecção de rações, matrizeiros e incubatórios. Apesar da predominância de contratos formais para negociação do frango, verificaram-se características de transações e termos de negociação bastante distintos nos três processos de integração realizado com empresas integradoras. Tais diferenças decorrem de formas de alianças estratégicas distintas em termos de ambientes organizacionais, características dos agentes e coordenação da cadeia produtiva. Pôde-se concluir também que não só os atributos das transações, mas também outros fatores influenciam as transações e estruturas de governança. Destacam-se o papel da confiança, o poder na relação e a dependência entre os agentes como fatores relevantes para compreensão das transações e estruturas de governança.    

39.	 MOREIRA, A. R. B.; HELFAND, S. M.; FIGUEIREDO, Adriano M.R. 2010.
Explicando as diferenças de pobreza entre produtores agrícolas no Brasil In XLVIII Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural XLVIII Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural Campo Grande MS 2010 1 1-1 Brasilia DF: SOBER
Palavras-chave: pobreza, agricultura, Brasil
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Economia Regional e Urbana
Setores de atividade: Agricultura, Pecuária, Produção Florestal, Pesca e Aqüicultura
Referências adicionais: Brasil/Português. Meio de divulgação: Vários. Home page: [http://www.sober.org.br]
O Censo Agropecuário 1995/96 é utilizado para estudar os fatores responsáveis pelas diferenças na pobreza entre os estabelecimentos agrícolas no Brasil. As diferenças entre as regiões e as seguintes dicotomias são analisadas: proprietários/não-proprietários; familiares/não-familiares; intensivos em insumos/não intensivos; com/sem máquinas. O artigo utiliza uma metodologia semi-paramétrica. Primeiro, uma função fronteira estocástica de lucro é estimada. Em seguida, simulações não paramétricas contrafatuais são utilizadas para identificar os fatores que explicam as diferenças em pobreza. Os fatores incluem o tamanho da propriedade, o trabalho familiar, a lucratividade e as variáveis utilizadas para explicar a lucratividade no modelo de fronteira estocástica. O artigo conclui que a escassez de terra e os baixos níveis de produtividade são importantes motivos para a pobreza entre os produtores agrícolas. É improvável que qualquer um deles isoladamente possa solucionar o problema da pobreza. As diferenças em “eficiência” – capturadas pelo termo de erro na função fronteira de lucro – são importantes para explicar as diferenças entre os pobres e não-pobres, mas não para as demais dicotomias estudadas. Isto sugere que os fatores não observáveis – como habilidade, restrições ou falhas de mercado – são importantes para explicar a pobreza entre os produtores agrícolas no Brasil.    

40.	 FIGUEIREDO, A. M. R.; BONJOUR, S. C. M.; MARQUES, A. K.; MANCILLA, G. D.. 2009.
A caracterizacao ambiental da pequena propriedade rural de Lucas do Rio Verde - Mato Grosso In Anais do XLVII Congresso da Sociedade Brasileira de Economia Administração e Sociologia Rural XLVII Congresso da Sociedade Brasileira de Economia Administração e Sociologia Rural Porto Alegre-RS 2009 47 1-1 Brasilia-DF: Embrapa/SOBER
Palavras-chave: Mato Grosso, pequenas propriedades, preservação ambiental, georeferenciamento
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais
Setores de atividade: Agricultura, Pecuária, Silvicultura e Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Vários. Home page: [http://www.sober.org]
This work aims to quantify and characterize the area of production and environmental preservation of small farms in the municipality of Lucas do Rio Verde, State of Mato Grosso. Thus, we used data of farms, production, cultivated land, preserved area, yield, type of credit and labor. The results show that the small farms have land productivity above the state’s average, while the preserved area is well below the minimum established by law. With satellite’s images and georeferenced data from the Lucas Legal Project, at farm level, we detected that small farms have a necessary area called legal reserve of 4,792 hectares for 1,318 hectares of conservation areas, or 3,473 degraded hectares. The estimated cost to recuperate the legal reserve area is between 17 and 24 million reais.    

41.	 DASSOW, C.; AZEVEDO JUNIOR, W. C.; COSTA, R.M.G.S.; FIGUEIREDO, A. M. R.. 2009.
Agropecuaria, Crescimento Economico e Convergencia de Renda Municipal em Mato Grosso In Anais do XLVII Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural XLVII Congresso da Sociedade Brasileira de Economia Administracao e Sociologia Rural Porto Alegre-RS 2009 47 1-1 Brasilia-DF: Embrapa/Sober
Palavras-chave: Crescimento Econômico, convergencia de renda, Econometria Espacial, Mato Grosso
Áreas do conhecimento: Economia Regional e Urbana,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária, Silvicultura e Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Vários. Home page: [http://www.sober.org.br]
Este trabalho investiga o efeito do setor agropecuário sobre o crescimento econômico e a convergência de renda dos municípios de Mato Grosso para o período de 2002 a 2005. Utilizou-se a teoria de convergência-β condicional, adaptando o modelo de Barro e Sala-i-Martin, e incorporando a metodologia econométrica espacial. Não existe dependência espacial detectada pelo teste global mas o teste de dependência espacial local (LISA) identificou um cluster de crescimento em uma região que é também pólo agropecuário do estado. Concluiu-se que há convergência-β condicional nos municípios mato-grossenses. Ainda, se constatou econometricamente que o setor agropecuário se mostra importante para o crescimento econômico dos municípios. No entanto, considera-se interessante aprofundar esses estudos, levando em consideração as características municipais e regionais, a fim de reduzir as suas desigualdades e obter um processo de crescimento econômico mais eficaz.    

42.	 BONJOUR, S. C. M.; PENHA, C.; FIGUEIREDO, A.; GUIMARAES, P. W.. 2009.
Uma análise de competitividade do complexo da laranja brasileira no período de: 1996 a 2005 In Actas do XV Congresso da Associacao Portuguesa de Desenvolvimento Regional XV Congresso da Associacao Portuguesa de Desenvolvimento Regional Cidade da Praia - Cabo Verde 2009 1 3071-3087 Porto: APDR
Palavras-chave: laranja, competitividade, concentracao
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária, Silvicultura e Exploração Florestal
Referências adicionais: Cabo Verde/Português. Meio de divulgação: Vários. Home page: [http://www.apdr.pt/congresso/2009/pdf/Sessão%2031/6A.pdf]    

43.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.; MARTA, J. M. C.. 2008.
A pecuaria de corte no estado de Mato Grosso In Anais do XLVI Congresso da SOBER XLVI Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural Rio Branco-AC 2008 46 1-20 Brasilia: SOBER
Palavras-chave: pecuária de corte, Mato Grosso, colonizacao
Áreas do conhecimento: Economia Agrária,Economia Regional e Urbana
Setores de atividade: Agricultura, Pecuária, Silvicultura e Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://serverbr7.com/~sober02/palestra/9/519.pdf]    

44.	 LAMERA, J. A.; ALVES, Janice; FIGUEIREDO, A. M. R.; ZAVALA, A.A.Z.. 2008.
Analise envoltoria de dados no estudo da eficiencia em assentamentos rurais no estado de Mato Grosso In Anais do XLVI Congresso da SOBER XLVI Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural Rio Branco-AC 2008 46 1-20 Brasilia: SOBER
Palavras-chave: assentamentos, DEA, Eficiência, Mato Grosso
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária, Silvicultura e Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://serverbr7.com/~sober02/palestra/9/197.pdf]    

45.	 MUCELLINI, A. B.; BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.. 2008.
Mudanças cambiais e os efeitos dos fatores de crescimento das receitas de exportacoes de algodao In Anais do XLVI Congresso da SOBER XLVI Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural Rio Branco-AC 2008 46 1-20 Brasilia: SOBER
Palavras-chave: taxa de câmbio, shift-share, algodão
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos,Relações do Comércio; Política Comercial; Integração Econômica
Setores de atividade: Agricultura, Pecuária, Silvicultura e Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://serverbr7.com/~sober02/palestra/9/635.pdf]    

46.	 LAMERA, J. A.; ALVES, Janice; FIGUEIREDO, A. M. R.. 2008.
Os Assentamentos Rurais em Mato Grosso In Anais do XLVI Congresso da SOBER XLVI Congresso da Sociedade Brasileira de Economia, Administração e Sociologia Rural Rio Branco-AC 2008 46 1-20 Brasilia: SOBER
Palavras-chave: assentamentos, reforma agrária, Mato Grosso
Áreas do conhecimento: Economia Agrária
Setores de atividade: Agricultura, Pecuária, Silvicultura e Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital. Home page: [http://serverbr7.com/~sober02/palestra/9/147.pdf]    

47.	 BONJOUR, S. C. M.; STIPP, F. E.; FIGUEIREDO, A. M. R.. 2007.
Análise de indicadores no comércio bilateral entre Brasil e China: 1996-2006 In VI Encontro Internacional do FOMERCO: Os novos rumos do Mercosul VI Encontro Internacional do Forum Universitario Mercosul - FOMERCO Aracaju-SE 2007 VI 1-1 Aracaju-SE: Universidade Federal de Sergipe
Palavras-chave: comércio internacional, indicadores de competitividade, China
Áreas do conhecimento: Economia Agrária,Relações do Comércio; Política Comercial; Integração Econômica
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal, Outros Setores
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital    

48.	 PEDRACA, J. S.; FIGUEIREDO, A. M. R.; BONJOUR, S. C. M.. 2007.
Análise do Programa de Aquisição de Alimentos (PAA): Compra Antecipada Especial da Agricultura Familiar em Mato Grosso In Anais do Congreso Latinoamericano y Caribeno de Ciencias Sociales Congreso Latinoamericano y Caribeno de Ciencias Sociales Quito 2007 1 1-1 Quito: FLACSO Ecuador
Palavras-chave: agricultura familiar, Desenvolvimento Rural, PAA
Áreas do conhecimento: Economia Agrária
Setores de atividade: Desenvolvimento Rural, Agricultura, Pecuária, Silvicultura, Exploração Florestal
Referências adicionais: Equador/Português. Meio de divulgação: Impresso
Publicação no prelo. Previsão de divulgacao para dezembro de 2007.    

49.	 MOREIRA, A. R. B.; HELFAND, S. M.; FIGUEIREDO, A. M. R.. 2007.
Determinantes da Pobreza do Produtor Agrícola no Brasil In Pobreza Rural no Brasil: o papel das políticas públicas Pobreza Rural no Brasil: o papel das políticas públicas Brasilia 2007 1 1-18 Rio de Janeiro: IPEA/BASIS
Palavras-chave: pobreza, Desenvolvimento Rural, agricultura, Brasil
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital
Artigo apresentado em seminario parte do projeto em convenio entre IPEA/BASIS-CRSP-USAID.    

50.	 FIGUEIREDO, A. M. R.; MOREIRA, A. R. B.; HELFAND, S. M.. 2007.
Explicando as diferenças na produtividade agrícola no Brasil In Conhecimentos para a Agricultura do Futuro XLV CONGRESSO DA SOBER Joint with AIEA2 Londrina-PR 2007 45 71-71 Londrina/Brasília: UEL/SOBER
Palavras-chave: produtividade, agricultura, Brasil
Áreas do conhecimento: Economia Agrária
Setores de atividade: Desenvolvimento Rural, Agricultura, Pecuária, Silvicultura, Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Vários. Home page: [http://www.sober.org.br]    

51.	 LAMERA, J. A.; ALVES, Janice; BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.. 2006.
O Crédito Rural Oficial e a Agricultura de Mato Grosso: 1993 a 2001 In Questões Agrárias, Educação no Campo e Desenvolvimento XLIV CONGRESSO DA SOBER Fortaleza 2006 44 1-1 Brasilia-DF: Sober
Palavras-chave: crédito rural, Mato Grosso, agricultura
Áreas do conhecimento: Economia Agrária
Setores de atividade: Produção Vegetal, Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Vários. Home page: [http://serverbr7.com/~sober02/palestra/5/366.pdf]    

52.	 MARTA, J. M. C.; FIGUEIREDO, A. M. R.. 2006.
Uma Interpretação Política da Introdução da Soja no Cerrado de Mato Grosso In Questões Agrárias, Educação no Campo e Desenvolvimento XLIV CONGRESSO DA SOBER Fortaleza 2006 44 1-1 Brasília-DF: Sober
Palavras-chave: Mato Grosso, soja
Áreas do conhecimento: Economia Agrária,Crescimento e Desenvolvimento Econômico
Setores de atividade: Desenvolvimento Rural, Produção Vegetal
Referências adicionais: Brasil/Português. Meio de divulgação: Vários. Home page: [http://serverbr7.com/~sober02/palestra/5/949.pdf]    

53.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.. 2004.
Administração Rural e Produtividade na Pecuária de Corte de Rondonópolis-MT In III Encontro Internacional da Pecuária - ENIPEC Encontro Internacional da Pecuária - ENIPEC Cuiabá 2004 Cuiabá - MT: FAMATO
Palavras-chave: carne bovina, Mato Grosso
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais
Setores de atividade: Produção Animal, Inclusive Serviços Veterinários
Referências adicionais: Brasil/Português. Meio de divulgação: Outro    

54.	 SOUZA, S. S. S.; FIGUEIREDO, A. M. R.; BONJOUR, S. C. M.; MARTA, J. M. C.. 2004.
Analise dos canais de comercializacao do algodao colorido no estado de Mato Grosso In Anais do XLII Congresso da Sociedade Brasileira de Economia e Sociologia Rural XLII Congresso da Sociedade Brasileira de Economia e Sociologia Rural Cuiaba-MT 2004 42 57-57 Juiz de Fora-MG: SOBER/UERJ/UFMT/Embrapa Gado de Leite
Palavras-chave: Canais de comercialização, algodão colorido, Mato Grosso
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal, Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Vários
Dinamicas Setoriais e Desenvolvimento Regional    

55.	 MARTA, J. M. C.; FIGUEIREDO, A. M. R.. 2004.
Analise dos negocios dos arranjos de produtos naturais na Baixada Cuiabana: uma economia de escopo In Anais do Congresso da Sociedade Brasileira de Economia e Sociologia Rural XLII Congresso da Sociedade Brasileira de Economia e Sociologia Rural Cuiaba-MT 2004 42 301-01 Juiz de Fora-MG: SOBER/UERJ/UFMT/Embrapa Gado de Leite
Palavras-chave: comercialização, Mato Grosso, recursos naturais
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal, Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Vários    

56.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.. 2004.
Carne bovina: um estudo prospectivo In III Encontro Internacional da Pecuária - ENIPEC III Encontro Internacional da Pecuária - ENIPEC Cuiabá 2004 Cuiabá: FAMATO
Palavras-chave: carne bovina, prospecção, comércio internacional
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais,Economia Internacional
Setores de atividade: Produção Animal, Inclusive Serviços Veterinários
Referências adicionais: Brasil/Português. Meio de divulgação: Outro    

57.	 BATISTA, F.; GOMES, N. G.; PILGER, T. E.; FIGUEIREDO, A. M. R.. 2004.
Centrogrãos: uma alternativa de comercialização de soja e financiamento agricola em Mato Grosso In Anais do Congresso da Sociedade Brasileira de Economia e Sociologia Rural XLII Congresso da Sociedade Brasileira de Economia e Sociologia Rural Cuiabá-MT 2004 42 61-61 Juiz de Fora-MG: SOBER/UERJ/UFMT/Embrapa Gado de Leite
Palavras-chave: comercialização, financiamento agricola, rentabilidade do produtor
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal, Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Vários    

58.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.; CAMPOS, A. C.. 2004.
Efeitos de alterações no consumo e nas exportações de carne bovina brasileira de diferentes sistemas produtivos In Anales del I Congreso Regional de Economistas Agrarios/II Congreso Rioplatense de Economia Agraria/XXXV Reunion Anual de la AAEA/IX Congreso de Economistas Agrarios de Chile I Congreso Regional de Economistas Agrarios/II Congreso Rioplatense de Economia Agraria/XXXV Reunion Anual de la AAEA/IX Congreso de Economistas Agrarios de Chile Mar del Plata, Argentina 2004 I 50-50 Mar del Plata: Universidad Nacional de Mar del Plata
Palavras-chave: carne, bovinos, Equilíbrio geral
Áreas do conhecimento: Economia Agrária,Economia Regional
Setores de atividade: Produção Animal, Inclusive Serviços Veterinários
Referências adicionais: Argentina/Português. Meio de divulgação: Vários. Home page: [http://www.ipcva.com.ar/files/trabajo27.pdf]
Congresso conjunto das Associações Nacionais de Economistas Rurais da Argentina, Chile e Uruguay.    

59.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.; CAMPOS, A. C.. 2004.
Mudancas na preferencia internacional de carne bovina e alteracoes nos precos e comercio exterior In Anais do Congresso da Sociedade Brasileira de Economia e Sociologia Rural XLII Congesso da Sociedade Brasileira de Economia e Sociologia Rural Cuiaba-MT 2004 42 175-175 Juiz de Fora-MG: SOBER/UERJ/UFMT/Embrapa Gado de Leite
Palavras-chave: carne bovina, Equilíbrio geral
Áreas do conhecimento: Economias Agrária e dos Recursos Naturais
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal
Referências adicionais: Brasil/Português. Meio de divulgação: Vários    

60.	 MIRANDA, O. C.; FIGUEIREDO, A. M. R.. 2003.
Análise da transmissão de preços na comercialização de arroz no estado de Mato Grosso, no período de 1991 a 2000 In XLI Congresso Brasileiro de Economia e Sociologia Rural XLI Congresso Brasileiro de Economia e Sociologia Rural Juiz de Fora-MG 2003 42 1-1 Brasília: SOBER
Palavras-chave: transmissão de preços, arroz, Mato Grosso
Áreas do conhecimento: Economia Agrária
Setores de atividade: Produção Vegetal
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital    

61.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.; CAMPOS, A. C.. 2003.
Estudo prospectivo da demanda de carne bovina In XLI Congresso Brasileiro de Economia e Sociologia Rural XLI Congresso Brasileiro de Economia e Sociologia Rural Juiz de Fora-MG 2003 42 1-1 Brasília: SOBER
Palavras-chave: prospecção, carne bovina
Áreas do conhecimento: Economia Agrária
Setores de atividade: Produção Animal, Inclusive Serviços Veterinários
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital    

62.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.. 2002.
Determinantes da produtividade da pecuária de corte (fase de engorda) no município de Rondonópolis-MT In Anais XL Congresso Brasileiro de Economia e Sociologia Rural XL Congresso Brasileiro de Economia e Sociologia Rural Passo Fundo, RS 2002 40 66-66 Brasília, DF: Sociedade Brasileira de Economia e Sociologia Rural
Palavras-chave: pecuária de corte, índices de administração, Mato Grosso
Áreas do conhecimento: Economia Agrária
Setores de atividade: Produção Animal, Inclusive Serviços Veterinários, Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital
Resumo impresso e texto completo no CD-Rom do evento.    

63.	 FIGUEIREDO, A. M. R.; TEIXEIRA, E. C.; LIMA, J. E.; HELFAND, S. M.; CAMPOS, A. C.. 2002.
Resposta da produção agrícola às alterações nos preços no centro-oeste brasileiro: uma análise de econometria espacial para o período 1975-1995/1996 In Anais XL Congresso Brasileiro de Economia e Sociologia Rural XL Congresso Brasileiro de Economia e Sociologia Rural Passo Fundo, RS 2002 40 55-55 Brasília-DF: Sociedade Brasileira de Economia e Sociologia Rural
Palavras-chave: autocorrelação espacial, dualidade, Centro-Oeste
Áreas do conhecimento: Economia Agrária,Métodos e Modelos Matemáticos, Econométricos e Estatísticos
Setores de atividade: Agricultura, Pecuária, Silvicultura, Exploração Florestal, Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital
Trabalho com resumo impresso e artigo completo no CD-Rom do evento.    

64.	 BONJOUR, S. C. M.; FIGUEIREDO, A. M. R.; TEIXEIRA, E. C.. 2002.
Uso de insumos na pecuária de corte do estado de São Paulo - 1990-2000 In Anais XL Congresso Brasileiro de Economia e Sociologia Rural XL Congresso Brasileiro de Economia e Sociologia Rural Passo Fundo, RS 2002 40 59-59 Brasília, DF: Sociedade Brasileira de Economia e Sociologia Rural
Palavras-chave: pecuária de corte, translog, substituição de insumos
Áreas do conhecimento: Economia Agrária
Setores de atividade: Produção Animal, Inclusive Serviços Veterinários, Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Meio digital
Resumo impresso e texto completo no CD-Rom do evento.    

65.	 FERREIRA, A. V.; FIGUEIREDO, A. M. R.; TEIXEIRA, E. C.. 1999.
Custos e benefícios de um programa de garantia de renda aplicado ao PRONAF In O Agronegócio do Mercosul e a sua Inserçao na Economia Mundial XXXVII Congresso Brasileiro de Economia e Sociologia Rural e First SOBER / IAAE Joint Symposium Foz do Iguaçu - Paraná-Brasil 1999 37 137-137 Brasília/DF: Sociedade Brasileira de Economia e Sociologia Rural
Palavras-chave: agricultura familiar, risco, garantia de renda
Áreas do conhecimento: Economia Agrária
Setores de atividade: Desenvolvimento Rural
Referências adicionais: Brasil/Português. Meio de divulgação: Vários
Trabalho apresentado fazendo análise do Programa de Garantia de Renda como um aperfeiçoamento ao PRONAF, visando minimizar o risco associado à renda da agricultura familiar, para produtores de feijão e mandioca, no período 1990/97.    

66.	 FIGUEIREDO, A. M. R.; FERREIRA, A. V.; TEIXEIRA, E. C.. 1999.
Impactos de alterações na política cambial sobre as relações de produção na cultura do café In O Agronegócio do Mercosul e a sua Inserção na Economia Mundial XXXVII Congresso Brasileiro de Economia e Sociologia Rural e First SOBER / IAAE Joint Symposium Foz do Iguaçu - PR - Brasil 1999 37 138-138 Brasília - DF: Sociedade Brasileira de Economia e Sociologia Rural
Palavras-chave: custo, câmbio, funções translog
Áreas do conhecimento: Economia Agrária
Setores de atividade: Desenvolvimento Rural, Produção Vegetal
Referências adicionais: Brasil/Português. Meio de divulgação: Vários
Trabalho apresentado analisando as relações de produção de café, utilizando funções translog, e um modelo de choques de desvalorização cambial afetando preços, produção e uso dos fatores.